create table questions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  content text check (char_length(content) > 3),
  answer text check (char_length(answer) > 3),
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create policy "Individuals can create questions." on questions for
    insert with check (auth.uid() = user_id);
create policy "Individuals can view their own questions. " on questions for
    select using (auth.uid() = user_id);
create policy "Individuals can update their own questions." on questions for
    update using (auth.uid() = user_id);
create policy "Individuals can delete their own questions." on questions for
    delete using (auth.uid() = user_id);
    